Remove Protein Expression Matrix assay
LabKey/commonAssays pull request #336
Opened 2021-05-20 23:11 UTC by labkey-martyp

#### Rationale
Per Josh's request, this assay is not being used so we can remove it.  This module is going to be deprecated so I did not refactor to completely remove all assay code, just removed it's registration.

#### Changes
* Remove assay provider registration from MS2Module

2021-05-21 19:28 UTC, labkey-klum commented
Unless we are planning to delete the module soon, I would vote to delete the implementation classes as well. It would be less code to build and maintain from refactors.

2021-05-24 16:47 UTC, labkey-jeckels requested changes
I agree with Karl. The MS2 module may get removed from the community edition, but it's not going to be totally deleted.

I hope that it's pretty painless to delete everything in the org.labkey.ms2.matrix package. I only see a few references to it, all in MS2Module where it registers implementations, including the assay provide that you've already deleted in this feature branch

2021-05-25 00:08 UTC, labkey-jeckels approved these changes

2021-05-26 22:53 UTC, labkey-klum approved these changes

2021-05-28 04:07 UTC, merged