Switch assay import to use DataIterator
LabKey/commonAssays pull request #780
Opened 2024-07-22 22:58 UTC by labkey-jeckels

#### Rationale
Building on earlier work to make assay import stream data to handle large files, using `DataIterator` for the streaming aligns this code with other streaming approaches.

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/5703

#### Changes
- New helpers for Map-oriented DataIterating
- Switch from the temporary `ValidatingDataRowIterator` to `DataIterator`
- Stronger enforcement of `DataIterator` assumptions

2024-07-23 23:48 UTC, labkey-matthewb requested changes
Opportunity for streaming by using DataLoader.getDataIterator()  (I'm not sure if everything ends up in memory anyway here).

2024-07-23 23:48 UTC, labkey-matthewb commented on viability/src/org/labkey/viability/ViabilityDataExchangeHandler.java
>                  List<Map<String, Object>> rows = parser.getResultData();
Parser is using a DataLoader internally.  Probably makes sense to skip the List<Map> step and have getResultData() return either DataLoader or DataIteratorBuilder.

2024-07-24 00:44 UTC, labkey-jeckels commented on viability/src/org/labkey/viability/ViabilityDataExchangeHandler.java
>                  List<Map<String, Object>> rows = parser.getResultData();
Based on metrics, there's one server in the world that has Viability data. (It's the only distribution that includes the module). It has ~5k runs, which average 18 rows of data. I'm not sure a refactor is worth the effort here since there are three parsing variants, one in `ViabilityAssayDataHandler` and two in `GuavaDataHandler`

2024-07-24 17:11 UTC, labkey-matthewb commented on viability/src/org/labkey/viability/ViabilityDataExchangeHandler.java
>                  List<Map<String, Object>> rows = parser.getResultData();
OK, I didn't know if this was specific to viability or a general assay thing.

2024-07-24 17:12 UTC, labkey-matthewb approved these changes

2024-07-29 21:38 UTC, merged